apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-jenkins 
  labels:
    app: app-1
spec:
  selector:
    matchLabels:
        app: app-1
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          image: [ECR-Repository-id].dkr.ecr.ap-southeast-1.amazonaws.com/app-1:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always