apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3-jenkins 
  labels:
    app: app-3
spec:
  selector:
    matchLabels:
        app: app-3
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
        - name: app-3
          image: [ECR-Repository-id].dkr.ecr.ap-southeast-1.amazonaws.com/app-3:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always